### ISSUE TITLE
username and password in POST payload?

### ISSUE THREAD

**Issue by nelsonic** [hapijs/hapi-auth-basic#38]
Hi @mtharrison 

At *present* the **hapi-auth-basic** plugin checks for the `username` and `password` in the `authorization` header per the [rfc2617 spec](https://www.ietf.org/rfc/rfc2617.txt) 

This has to be [**base64**](https://github.com/hapijs/hapi-auth-basic/blob/3bb813018819bf21f05f01a1db2b158db2878bfc/test/index.js#L746) encoded Buffer which is not immediately apparent in the README.

Also requiring the `username` and `password` to be sent in the auth header is not as beginner-friendly to as sending them in POST `payload` ... *would* you accept a ***pull request*** extending the plugin to accept the credentials via `payload` (*with tests and additions to the readme*) ?

**Comment by mtharrison** [comment]
This wouldn't work as requests are authenticated before payloads are parsed (or even read) in hapi. See: http://hapijs.com/api#request-lifecycle. 

It would be wasteful to read a payload in memory that you're just going to discard. Not to mention I don't think this would even be Basic Authentication anymore, browser wouldn't cache credentials for you etc.

I'd welcome a PR on the docs if you think we can make them clearer though.

**Comment by nelsonic** [comment]
You're right, I should split out those two questions into separate issues. I'll simplify it. Thanks for the quick reply. :+1:

**Comment by johnbrett** [comment]
Hey @nelsonic, if you're looking for something a bit more beginner friendly [hapi-auth-bearer-token](https://github.com/johnbrett/hapi-auth-bearer-token) lets you pass in your token in the url by just adding ?access_token=TOKEN to the url. obviously less secure, but easier for beginner examples.

**Comment by nelsonic** [comment]
Thanks @johnbrett :+1:
