### ISSUE TITLE
Node >= 4 / es2015 updates

### ISSUE THREAD

**Issue by mtharrison** [hapijs/hapi-auth-basic#42]
Summary of changes required:

- use strict
- `const` and `let` where appropriate
- arrow functions where appropriate
- relevant updates to tests + docs
- updating the engine in package.json

**Comment by hueniverse** [comment]
Also, avoid `self` and `+=` / `-=` (not optimized yet for let const)

**Comment by devinivy** [comment]
Are you saying that `var` should be used with `self = this` rather than `let`?

**Comment by mtharrison** [comment]
@devinivy Avoiding altogether I think: https://github.com/hapijs/shot/commit/129d6f683f0539a8770571ae9aefd397ccf87803#diff-6d186b954a58d5bb740f73d84fe39073L83

**Comment by katherine-barn2door** [comment]
Is there a list of the breaking changes? 

I found this was definitely breaking when I went from 2.x to 4.x. I'm wondering if there's anything else.

https://github.com/hapijs/hapi-auth-basic/commit/92b2e60d660ec76b11502dc51917a7874c82f862
