### ISSUE TITLE
chain strategies

### ISSUE THREAD

**Issue by AdriVanHoudt** [hapijs/hapi-auth-basic#45]
I recently matched my error handling with this plugin thinking this was a good example, turns out this plugin does not allow chaining strategies or am I doing something wrong?

**Comment by mtharrison** [comment]
What are "chaining strategies"? You mean setting multiple strategies on a route to attempt them all? Do you have some code so I can see what mean?

**Comment by AdriVanHoudt** [comment]
yes and not directly
see
```
When the scheme authenticate() method implementation calls reply() with an error condition, the specifics of the error affect whether additional authentication strategies will be attempted if configured for the route. If the err returned by the reply() method includes a message, no additional strategies will be attempted. If the err does not include a message but does include a scheme name (e.g. Boom.unauthorized(null, 'Custom')), additional strategies will be attempted in order of preference.
```
and see https://github.com/hapijs/hapi-auth-basic/blob/master/lib/index.js#L69-L81
the module always returns an error with a message so making chaining impossible

**Comment by mtharrison** [comment]
It will only move onto the next strategy if the current one can't be tried. By that line that you're referencing it's already got round to validating the Authenticate header. Which means that strategy is a valid one to test. If if fails, that's game over right then.

If however you made a request without an Authentcate header at all, if would fail [here](https://github.com/hapijs/hapi-auth-basic/blob/master/lib/index.js#L39) and then move onto the next strategy if there was one.

[Similar discussion here](https://github.com/hapijs/hapi/issues/2654).

**Comment by AdriVanHoudt** [comment]
ok so this means it is not meant/not a good strategy to try 1 auth strategy and if it fails try the next one?

**Comment by mtharrison** [comment]
Well, it seems it's definitely not how it was designed to work. In terms of whether it's a good thing to do or not, I can't see a use case for it.

If you specify auth scheme using a cookie called 'my-cookie' and then request provides a cookie called 'my-cookie' it feels like the request should be authenticated on the validity of that cookie alone.

If the request doesn't provide a cookie at all, or a cookie called something else it makes sense to try another strategy then.

**Comment by AdriVanHoudt** [comment]
So my use case is that we use bearer tokens and you have user tokens and team tokens, the route should work for both but it is only on a few routes

**Comment by mtharrison** [comment]
Are you using hapi-auth-bearer-token? If you name the tokens (`tokenType`) differently it will try both: https://github.com/johnbrett/hapi-auth-bearer-token/blob/master/lib/index.js#L58

**Comment by AdriVanHoudt** [comment]
Hapi-auth-bearer-simple ;) but I will check that out thanks!

**Comment by mtharrison** [comment]
No problem

**Comment by fedirch** [comment]
Hi,
Have one question regarding JWT tokens validation. What would be the design if I need to validate such tokens that are issued by different issuers. So, the schema will remain the same, just the secret will be different. It would be good to try all of them until proper is found.

What would you recommend?

Thanks,
Fedir

**Comment by Jiropole** [comment]
@fedirch I know this was a while back now, but did you ever find a solution for this use case?

**Comment by fedirch** [comment]
@Jiropole , as of now I created custom auth, based on jasonwebtoken and hapi-auth-jwt2. in hapi-auth-jwt i used not validateFunc, but verifyFunc. It allows to have custom verification of the token, I tries different keys in parallel (Proomise.all) and on done check if any is resolved.

**Comment by Jiropole** [comment]
Thanks @fedirch! I actually did defeat my own ignorance a few hours later and the multi-tenant solution is just as compact as the original. 

One note of difference, I do not check all keys; only the one corresponding to (in our case) the audience value. Not sure if that's better or same security, but it seems simpler to implement.
