### ISSUE TITLE
How do you retrieve credentials in a route handler?

### ISSUE THREAD

**Issue by jhyland87** [hapijs/hapi-auth-basic#47]
I'm trying to use the **hapi-auth-basic** plugin to perform basic authentication for an account, and on success, return a JWT token that will be generated and used by **[hapi-auth-jwt](https://github.com/ryanfitz/hapi-auth-jwt)**. I can get the authentication working just fine via hapi-auth-basic, I just need to generate the key, and to do that, I need the username. I looked through the request object (first param in the route handler), but I didnt see it, where can I grab the credentials?

Thanks

**Comment by askerb** [comment]
In your api-auth-basic validate function where you have all credentials, you can include a custom credentials object as the last parameter to the callback, put whatever you want in it:
 callback(err, isValid, { id: user.id, name: user.name });

The credentials object is then available in your api handlers as "request.auth.credentials"

**Comment by jhyland87** [comment]
Yep, thanks, I actually JUST figured it out and was coming here to comment on it and close it.

I see I can add the username to the callback in the `validateFunc` value, then retrieve it via `request.auth.credentials`.

Thanks!

**Comment by jhyland87** [comment]
P.S. Thanks for the quick response!
