### ISSUE TITLE
Clarification on register() function

### ISSUE THREAD

**Issue by jdmarshall** [hapijs/hapi-auth-basic#49]
It seems like the calling conventions for the server.register function have evolved over time, and it's not particularly clear how to wire up hapi-auth-basic in the register() function, especially if another plugin is already being registered.

For instance, 
```
server.register(
    [
        {
            register: require('hapi-bookshelf-models'),
            options: {
                knex: {
        ...
    },
    function(err) {
        ...
   }
```

and I can't figure out how to slot in Basic into this style of invocation.  Any help?

**Comment by mtharrison** [comment]
I don't think anything has changed that should affect this plugin. Just register it as usual [according to the docs](http://hapijs.com/api#serverregisterplugins-options-callback):

```javascript
server.register([
    require('some-plugin'),
    {
        register: require('some-other-plugin-with-options'),
        options: {
            ...
        }
    },
    require('hapi-auth-basic')
], (err) => {

    ...
});
```

The README also has an example. Going to close but please reopen if there's more questions or a specific error you have.
