### ISSUE TITLE
Usage with Lab testing framework

### ISSUE THREAD

**Issue by Chatatata** [hapijs/hapi-auth-basic#52]
Could you please provide a way to test endpoints protected with this authentication strategy?

Hapi's `server.inject` method has authentication object in its options, how can one provide credentials to this object?

I've tried this so far:

    server.inject({
        method: 'GET',
        url: '/users',
        auth: {
            username: 'admin',
            password: 'password'
        }
    }, function (response) {
        //  assertions...

        done();
    });

**Comment by Marsup** [comment]
It's already documented in inject itself (http://hapijs.com/api#serverinjectoptions-callback), you have to use `credentials`.

**Comment by Chatatata** [comment]
I apologize I missed that. Thank you.
