### ISSUE TITLE
Best way to Hide/Alter `WWW-Authenticate` header

### ISSUE THREAD

**Issue by shaunwarman** [hapijs/hapi-auth-basic#54]
There is probably a better way, but I was adding route level configuration in hapi for `cors: { exposedHeaders: [''] }` to eliminate the `WWW-Authenticate` header locally to get around google chrome's `Authentication Required` pop-up. Is there a better way to go about this?

Do others use something like `onPreResponse` to Alter `Basic ...` to something like `X-Basic ...` to get around browser triggers in this way. I obviously want to handle the form myself.

**Comment by hoboman313** [comment]
@shaunwarman How did you resolve your issue? This www-authenticate thing is so damn annoying.

**Comment by shaunwarman** [comment]
From initial check, I believe I was just adding `cors.exposedHeaders: ['']` [route option](https://hapijs.com/api#route-options). I feel like I came to some obvious realization after opening this though and I can't think of it now.

**Comment by agchou** [comment]
@shaunwarman @hoboman313 I added `cors.exposedHeaders: ['']` but got the error that empty is not allowed. Did you all get this and how did you get around it? I couldn't figure it out.
