### ISSUE TITLE
Can I Use A Form To Set Auth Headers?

### ISSUE THREAD

**Issue by mattc41190** [hapijs/hapi-auth-basic#56]
Hello hapi-auth-basic,

I am tinkering with your plugin and want to use a web form to set my authorization. Is this possible? Looking at your code I don't know what triggers the HTTP Auth modal to appear in my browser.

I probably have a shitty understanding of the way that authentication is supposed to occur in hapi, but the flow I naively want is.

``` syntax javascript
{
  method: 'POST',
  path: '/login', 
  config: {
    handler: function(request, reply) {
      var username = request.payload.username;
      var password =  request.payload.password;

      request.headers.authorization = // Set the auth header to "Basic base64unamepass" 

      return reply.redirect('/secretPageThatTequiresTheBasicAuthStrategy');
    }
  }
},
```

Then instead of the ugly little prompt asking me to put in my uname and pass it just refers to what i set in the login and I take advantage of the plugin to handle isAuthenticated and credentials.

If I am way off base please refer me to what you guys think is the best option.

**Comment by hueniverse** [comment]
The browser reacts to the Basic auth challenge coming from the server when auth is missing. If you want a custom auth form to enter username and password, you will need to create a custom auth scheme or use the hapi-auth-cookie scheme with a web form. I don't have time to help beyond this. In general, asking on hapijs/discuss will yield better results.

**Comment by mattc41190** [comment]
@hueniverse thanks for the response and redirect!
