### ISSUE TITLE
[Question] Can I use this without hapi?

### ISSUE THREAD

**Issue by lonix1** [hapijs/hapi-auth-basic#67]
I'm using Express rather than hapi. The defactor auth library there is express, which hasn't been maintained in years.

Then I found this. Am I able to use it without hapi?

**Comment by devinivy** [comment]
This library is built as a hapi plugin designed to work with hapi's authentication system, so it cannot be used directly with express.  There is a community plugin named [hecks](https://github.com/hapipal/hecks), however, that allows you to mount an express application as a hapi route, and that would allow you to place hapi auth in front of express.
